version: '3'

services:
  service-name:
    container_name: service-name
    hostname: service-name
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      - /usr/app/bin
    build:
      context: .
    environment:
      - ENV
      - BUILD_VERSION=local-build # DO NOT SPECIFY WHEN DEPLOYING TO STAGE
      - NODE_ENV=${ENV} # CAN ONLY BE 'local' OR 'production', hardcode to 'production' WHEN DEPLOYING TO STAGE AND PROD
    logging:
      driver: 'json-file'
      options:
        max-size: '5m'
        max-file: '2'
networks:
  default:
    name: special-projects
    external: true
