version: '3'

services:
  service-name:
    container_name: service-name
    hostname: service-name
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      - /usr/app/bin
    build:
      context: .
    environment:
      - ENV
      - BUILD_VERSION=local-build
      - NODE_ENV=${ENV}
    logging:
      driver: 'json-file'
      options:
        max-size: '5m'
        max-file: '2'
networks:
  default:
    external:
      name: special-projects
